[2024-06-24T03:17:34.336+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rbroker_account_dag.get_list_of_results scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T03:17:34.349+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rbroker_account_dag.get_list_of_results scheduled__2024-06-23T00:00:00+00:00 [queued]>
[2024-06-24T03:17:34.350+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2024-06-24T03:17:34.372+0000] {taskinstance.py:1382} INFO - Executing <Task(_PythonDecoratedOperator): get_list_of_results> on 2024-06-23 00:00:00+00:00
[2024-06-24T03:17:34.380+0000] {standard_task_runner.py:57} INFO - Started process 1337 to run task
[2024-06-24T03:17:34.385+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'rbroker_account_dag', 'get_list_of_results', 'scheduled__2024-06-23T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/staging/rbroker/rbroker_account_dag.py', '--cfg-path', '/tmp/tmpzh8hrnz2']
[2024-06-24T03:17:34.387+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask get_list_of_results
[2024-06-24T03:17:34.462+0000] {task_command.py:416} INFO - Running <TaskInstance: rbroker_account_dag.get_list_of_results scheduled__2024-06-23T00:00:00+00:00 [running]> on host b00a3d1afa8e
[2024-06-24T03:17:34.570+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rbroker_account_dag' AIRFLOW_CTX_TASK_ID='get_list_of_results' AIRFLOW_CTX_EXECUTION_DATE='2024-06-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-23T00:00:00+00:00'
[2024-06-24T03:17:34.594+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/staging/rbroker/rbroker_account_dag.py", line 15, in get_list_of_results
    results = hook.get_records("SELECT * FROM grocery_list;")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 255, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 125, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `database_conn` isn't defined
[2024-06-24T03:17:34.601+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=rbroker_account_dag, task_id=get_list_of_results, execution_date=20240623T000000, start_date=20240624T031734, end_date=20240624T031734
[2024-06-24T03:17:34.623+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task get_list_of_results (The conn_id `database_conn` isn't defined; 1337)
[2024-06-24T03:17:34.639+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-24T03:17:34.681+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
